name: Generate metrics

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  metrics:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: isometric calendar + introduction + wakatime
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          user: zacknguyn
          base: header
          template: classic
          config_timezone: Asia/Ho_Chi_Minh
          filename: github-metrics.svg

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, languages, editors, os
